### ISSUE TITLE
[Feature Request] Execute Slash Commander from the Command Palette

### ISSUE THREAD

**Issue by FelipeRearden** [alephpiece/obsidian-slash-commander#1]
Hello  @alephpiece !!!!!

First of all, I just wanna say how grateful I am to you about this plugin. 

I have been wanting to use the core plugin `Slash Commands` for a long time and your plugin targets exactly my pain points from. Thank you very much for this creating this plugin 🙏

The way that you integrated with Commanders core ideas is perfect for powers users :)

## My FR

My FR is about an additional workflow that I wanna build around `Slash Commander` 

The FR is simple to explain: would you mind adding the internal command that triggers the `Slash Commander` as a command that could be executed from the Command Palette **without the need to type a keyword**

I know that sounds weird, but let me explain this additional workflow that need 🙏

## My Workflow

I would like to open the `Slash Commander` context menu using a keyboard hotkey when I have **selected text** in the note.

This way, I can apply many commands using the selection like: decorations, backlinks and running URL schemes to translate the selected content. 

This way I can expand my usage of `Slash Commander` when I have text selected as well. 

---
Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by alephpiece** [comment]
Thanks very much for your idea!

Is a command palette only for Slash Commander what you need, like triggering Slash Commander by a hotkey, say `Ctrl + Shift + P` or something?

**Comment by alephpiece** [comment]
This is the first case I'm thinking about. Slash commands show up as editor suggestions. Since the cursor is on some selection, there is no room for you to filter the suggestions. So a search bar must be provided or commands would only be available by mouse clicking.

![image](https://github.com/alephpiece/obsidian-slash-commander/assets/22237751/2762ae0c-25f0-4328-adf1-51037f9e3004)

The second case seems simpler.  Slash commander will get a standalone palette, just like the default command palette. This palette is a modal dialog, which should work but seems weird. This workflow works just like choose `Toggle bold` from the command palette after making a text selection.

![image](https://github.com/alephpiece/obsidian-slash-commander/assets/22237751/31cf1725-799e-4b0a-bc31-dc758949a015)

**Comment by alephpiece** [comment]
A third case is to add slash commands to the right-click context menu, like what Commander plugin did.

**Comment by FelipeRearden** [comment]
> Thanks very much for your idea!
> 
> Is a command palette only for Slash Commander what you need, like triggering Slash Commander by a hotkey, say `Ctrl + Shift + P` or something?

Hello @alephpiece !!!!

Thank you very much for the reply :)

Yes, that exactly my FR  instead of type `/` (or another trigger key) I would like to open the `Slash Commander` using a `Ctrl + Shift + P` like you suggest. 

This simple addition would let me use `Slash Commander` when text is selected in the note which is my pain point today :)

Let me know if you need more information :)

**Comment by FelipeRearden** [comment]
@alephpiece !

If you allow me, I just wanna add my humble opinion about 1️⃣ 2️⃣ 3️⃣ cases. 

For me, the way that `Slash Commander` is right now is the PERFECT state because is unique, fast ,it’s tiny and is a custom context menu where the user can customize the commands and the icons the way they need. This what makes your plugin so unique, because its a fast way to execute a command without putting another big UI in the face of the user blocking the text that I am writing.

Please keep the UI beautiful as is today 🙏 🙏 🙏

I wish you a great day ☀️

**Comment by alephpiece** [comment]
Thanks for your information! That really helps a lot!

There is a `Format` right-click submenu in the newly released Obsidian (1.5.2, insider only). Is that close to what you want?

![image](https://github.com/alephpiece/obsidian-slash-commander/assets/22237751/faa8b9ac-3383-41ad-9c1f-79bbb792b3b8)

**Comment by FelipeRearden** [comment]
> Thanks for your information! That really helps a lot!

😀
 
> There is a `Format` right-click submenu in the newly released Obsidian (1.5.2, insider only). Is that close to what you want?

No :) This FR is just about opening slash commander from the Command Palette instead of using a keyword trigger.

- It is not necessary to have a separated section with commands that only opens when text is selected. 

It is very simple approach, just open/show the Slash Commander suggestions without losing the selected text  :)

Let me know if you need more information 😀

**Comment by alephpiece** [comment]
I'm working on a standalone menu now. My initial implementation would be putting a hotkey-triggered menu into work. It will show all the slash commands added to Slash Commander.

After that, I will try to make it possible to filter menu items.

**Comment by FelipeRearden** [comment]
> I'm working on a standalone menu now. My initial implementation would be putting a hotkey-triggered menu into work. It will show all the slash commands added to Slash Commander.
> 
> After that, I will try to make it possible to filter menu items.

That’s amazing news @alephpiece !!!!!

Thank you very much for creating this new Feature !!!! 🙏

I wish you a fantastic day ☀️

**Comment by alephpiece** [comment]
This feature is available now! It is still experimental, so please feel free to let me know you have any problems with this feature.

![slash-commander-standalone-menu](https://github.com/alephpiece/obsidian-slash-commander/assets/22237751/5a214107-1463-4eb7-95a3-feedaadf371c)

**Comment by FelipeRearden** [comment]
> This feature is available now! It is still experimental, so please feel free to let me know you have any problems with this feature.

Hello @alephpiece !!!!

Thank you very much for the new feature !!!!!
 
I have been testing version 0.2.3 and 0.2.5 since I saw your message and I have something specific for OBSIDIAN MOBILE to share with you. 

I am gonna try my best to explain in details that issue that only **OCCURS IN OBSIDIAN MOBILE**

100% working perfect on Obsidian Desktop

## Assumptions

● I am using an iPadOS 17 with mouse and keyboard;

● I am running the lastest public version of obsidian mobile;

● I tested on version 0.2.3 and 0.2.5 

● This only happens on Obsidian Mobile on iPad. It **NOT** occurs when emulating Obsidian Mobile on Desktop using the command below:

![IMG_0761](https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/3a126b4e-9bd4-40c4-9536-84f225276c4d)


## The Issue

it is simple explain. Two things happens after hitting <kbd>ENTER</kbd> to execute a command inside the MENU:

1️⃣ The MENU keeps visible in the UI

2️⃣ The command is executed TWO times in the active Note.

Follow below a screen record to show the issue

● I am gonna execute the command `Callout`
● Look at the right side of the screen to see the that the command is been executed 2 times

📹

https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/92bd5d03-03c8-479f-96e4-777578176125




<hr> 

Forgive for bring more problems 🙏
I hope you could find a solution for Mobile 🙏

Let me know if you need more tests !
I wish you a fantastic day ☀️

**Comment by alephpiece** [comment]
Thanks for your feedback, it's very informative!

I don't have an ipad at hand and only have tested this plugin on desktop. But this bug might be caused by the suggester I got from another project. I'll put the fix to a pre-release.

**Comment by FelipeRearden** [comment]
> Thanks for your feedback, it's very informative!
> 
> I don't have an ipad at hand and only have tested this plugin on desktop. But this bug might be caused by the suggester I got from another project. I've put a possible fix to 0.2.6.

Amazing !!! Testing right now the new version and I get back to you in a few minutes 🙏 🙏 🙏 🙏 🙏

**Comment by FelipeRearden** [comment]
> I've put a possible fix to 0.2.6.

Almost @alephpiece !!!!!

As you can see from the video below, the only issue that remais is that the menu keeps opened after executing the command. 


https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/5b2af9f6-15b3-4b53-bc5c-54e12058ecee



Maybe something triggers on your mind to force the closing the Menu after executing the command 🙏 🙏 🙏 🙏

Thanks for the help !!!!!!

**Comment by alephpiece** [comment]
Have you tried the escape key or mouse clicking on some space area? Does the menu disappear?

**Comment by FelipeRearden** [comment]
> Have you tried the escape key or mouse clicking on some space area? Does the menu disappear?

✅ Hitting <kbd>ESCAPE</kbd> closes the menu 🙏
❌ Mouse clicking does not disappear. I clicked on everything and does not disappear 

Forgive me for bring you more problems :)

**Comment by alephpiece** [comment]
> > Have you tried the escape key or mouse clicking on some space area? Does the menu disappear?
> 
> ✅ Hitting ESCAPE closes the menu 🙏 ❌ Mouse clicking does not disappear. I clicked on everything and does not disappear
> 
> Forgive me for bring you more problems :)

The menu disappears whenever the invisible text box loses focus. Maybe it's not the case on ipad. I commit a possible fix, again. Hope that helps!

**Comment by FelipeRearden** [comment]
> The menu disappears whenever the invisible text box loses focus. Maybe it's not the case on ipad. I commit a possible fix, again. Hope that helps!

Thank yuo very much @alephpiece !!!!!!!!! 

Testing right now and I get back to you in a few minutes 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏 🙏

**Comment by alephpiece** [comment]
Thanks for your help! If it doesn't work, I will test this feature on ipad asap.

**Comment by FelipeRearden** [comment]
Working PERFECT on version `0.2.7` on iPadOS on Obsidian Mobile version `1.4.16 ` !!!!!!!!!!

@alephpiece !!! thank you very much for the fix and for the patience. I really appreciate your help on this FR and on this fix ☀️

I am gonna start implementing my complex workflow using `Slash Commander` and `Slash Commander Standalone` commands. I am gonna stress this commands and I get back to you if something appears.

Again, my deepest thank for you help 🙏☀️

**Comment by alephpiece** [comment]
That's great! Thanks for your idea! I am so thankful for your tests on ipad. Please feel free to give your feedback on anything.

**Comment by FelipeRearden** [comment]
> That's great! Thanks for your idea! I am so thankful for your tests on ipad.

Thanks for the feedback !

> Please feel free to give your feedback on anything.

Okay, I will !!!!!!

**Comment by FelipeRearden** [comment]
Hello @alephpiece !!!!!!!

I think I found a bug in the command `Slash Commander: Standalone` . 

First let me point some things:

● Only happens on iPadOS
Not happens when Emulating Obsidian Mobile on Desktop :(

● Only happens on `Slash Commander: Standalone`

● This only happens on Obsidian Mobile on iPad. It **NOT** occurs when emulating Obsidian Mobile on Desktop

● 100% working perfect on Obsidian Desktop

● I think I know what to do avoid this BUG

## The Issue

This only happens when the note has an amount of lines higher than the screen.  in other words: when the note in scrolled;

By this I mean if that it only happens on larger notes when executing `Slash Commander: Standalone` in a line that is not in the begining of the note (like line 40 or 100 for example) in a way that your note is **scrolled** while executing the command. 

As you will se below, AFTER executing a command from `Slash Commander: Standalone` the note position **CHANGES** and **JUMPS** to the begin of the note losing the active line.

● Line 40 keeps being the active line, but the note is scrolled to line 0

https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/ca5b1cfe-52c6-4959-ab2a-c32ef898d8f7

● if I hit the command `Focus on Last Note` , it will go back to correct note position in the screen.

https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/e7b32fb5-43b5-4ec8-9b5d-1a3484c9d465

In other words, `Slash Commander: Standalone` is losing the focus on the active line after executing a command.

## I think I know Why :)

Before, some context:

I have been using Obsidian on iPadOS (with mouse and keyboard) and on Desktop for almost 3 years.

And I struggle a lot with Obsdian Mobile caret cursor until I figure out the Obsidian mobile behavior and changed my templater scripts. 

In a nutshell: Obsidian Mobile loves to lose the **caret cursor** when opening prompts. To avoid this (get the caret cursor back to the active line) a few years ago they created a command to manually force the caret cursor to stay in the active line.

The command name is `Focus on Last Note`

```
app.commands.executeCommandById('editor:focus')
```

<hr>

## An Idea to Solve this Issue on Mobile

When you said about **FUZZY SEARCH** in this comment [here](https://github.com/alephpiece/obsidian-slash-commander/issues/5#issuecomment-1868303398) something triggered in my mind.

When we are executing `Slash Commander: Standalone` to be able to **fuzzy search** without **hurting the selection** the caret cursor IS NOT FOCUSED in the Active Line.

This way, when we finish the execution of the command, Obsidian dont know anymore where the caret cursor was before the execution (since the caret cursor was in the fuzzy search) and it scrolls to the begin of the note. 

MY IDEA: I think if you disable the fuzzy search for the command `Slash Commander: Standalone` on Obsdian Mobile, it will solve the issue since the caret cursor will stay always in the same location.

💡 Look how different is when we use Trigger Command that is because the caret cursor is never lost  in the active line

While I am searching, the caret cursor is not lost. Look at the words after `/` while searching.


https://github.com/alephpiece/obsidian-slash-commander/assets/85180696/e833deb3-a42f-4498-b9b2-fd2bb67cc81d


💡 This BUG does not happens on `Context Menu` because there is not support for fuzzy search. 

<hr> 

Forgive for bring more problems 🙏

I did my best to try to help to investigate the issue since you can debug :(

Let me know if you need more tests !

I hope you could find a solution for Mobile 🙏

I wish you a fantastic day ☀️

**Comment by FelipeRearden** [comment]
Hello @alephpiece !!!!

UPDATE from my previous comment reporting a possible BUG [here](https://github.com/alephpiece/obsidian-slash-commander/issues/1#issuecomment-1868337196) in the post before this:

I think I found the issue: it was MY mistake while creating the commands that will be triggered by `Slash Commander Standalone ` . 

This way, I kindly ask you to not consider the Bug Report right now. Let me stress more in my real workflow with my commands to see if the issue that I reported before is really occurring. 

Forgive for the false alarm, I happy to know that I was on my end 🙏.

**Comment by alephpiece** [comment]
Thanks @FelipeRearden ! This sounds like a potential bug but I can't reproduce it.

I didn't force the suggester to return focus to the editor after a command execution. I think a command execution from the standalone menu is like that from the command palette. I assume that these editor commands need to know the editor context and return focus to the last active line automatically.

**Comment by FelipeRearden** [comment]
> I didn't force the suggester to return focus to the editor after a command execution. I think a command execution from the standalone menu is like that from the command palette. I assume that these editor commands need to know the editor context and return focus to the last active line automatically.

100% understood @alephpiece !!! 

I think it was a mistake from my end when creating the command that is been executed by Slash Commander. After this, it is working perfect on iPadOS. 

Feel free to close again thus issue :) I let you know if I find something :)
Have a grea day ☀️
