### ISSUE TITLE
Command trigger doesn't work with "Space" character

### ISSUE THREAD

**Issue by Hugo-COLLIN** [alephpiece/obsidian-slash-commander#11]
**Really thanks for this time-saver plugin!**

### Issue:
**I want to press the spacebar to open the menu**, but when I specify a space in the "Command trigger" option and try it on a note, **the menu is not appearing**. Please make it possible with Space character, it's more convenient than `/` for a french azerty keyboard.

1. Working with /
![image](https://github.com/alephpiece/obsidian-slash-commander/assets/101000595/de207506-98f9-4bf4-a627-bfecd58db606)

2. Changing to Space charater
![image](https://github.com/alephpiece/obsidian-slash-commander/assets/101000595/725e9021-becd-4450-aaf9-1a6d10ee7958)

3. Trying with Space character, not appearing.
![image](https://github.com/alephpiece/obsidian-slash-commander/assets/101000595/137ee4c1-5985-4e7a-9471-442291832d46)

**Comment by alephpiece** [comment]
I've released 0.1.16 for this, simply by not ignore the leading spaces of a new line. For now, the space trigger only takes effect in the new-line-only mode. Any spaces in a sentence will still be considered word delimiters.

**Comment by Hugo-COLLIN** [comment]
@alephpiece Thank you for your quick response! Works well now 👍

> For now, the space trigger only takes effect in the new-line-only mode.

Please specify it in the "Command trigger" description, it will save other people from asking the question.
