### ISSUE TITLE
[Feature Request] Add More than ONE Command Trigger

### ISSUE THREAD

**Issue by FelipeRearden** [alephpiece/obsidian-slash-commander#4]
Hello again @alephpiece !!!!

Fist of all, I have been using `Slash Commander` daily and its been AMAZING !!!!

This FR is simple to exaplain: add a way to define more than on `Command Trigger` 

I have been using `/` as my command trigger but based in my keyboard typing strategy I would like to add to more characters as `Command Triggers`. In my case would be `,` and `.` 

This way, this FR is to check with you if would be possible to add this feature 🙏

<hr>

Let me know if you need more information !!!

Have a great day 🌞

**Comment by alephpiece** [comment]
This is a fairly natural extension to this plugin, thanks very much for your idea!

**Comment by FelipeRearden** [comment]
> This is a fairly natural extension to this plugin, thanks very much for your idea!

Thanks @alephpiece !!!

**Comment by alephpiece** [comment]
This FR is done. Please let me know if this feature breaks anything, thank you！

**Comment by FelipeRearden** [comment]
> This FR is done. Please let me know if this feature breaks anything, thank you！

Working perfect on version `0.2.12` on iPadOS 17.1 🙏

@alephpiece thank you very much for this amazing feature ☀️

**Comment by alephpiece** [comment]
Thank you for the idea of multiple triggers! It makes this plugin super flexible now!

**Comment by FelipeRearden** [comment]
> Thank you for the idea of multiple triggers! It makes this plugin super flexible now!

yeah ! step by step we are bring more options to powers users :)
