### ISSUE TITLE
[Feature Request] 针对“新行”和非“新行” 使用两套命令配置

### ISSUE THREAD

**Issue by alexinea** [alephpiece/obsidian-slash-commander#7]
针对“新行”和非“新行” 使用两套命令配置

因为有些命令可以在非新行中使用，比如插入链接、Highlightr 标记、`<kbd>`、Subscript、Superscript 行内代码标记等。

分开配置后，我们可以大胆关闭”仅用于新行“配置，在行内不会因为打开选了个 Table 而把整行给弄没了。

---

btw，“额外的触发符” 10086 个好评，中文顿号有救了。

**Comment by alephpiece** [comment]
这个功能很好啊！马上搞！

**Comment by alephpiece** [comment]
我暂时给每个命令都增加了一个选项，选项值可以是“新行”、“行内”或者“新行+行内”，分别对应三种触发情况。如果这样不方便的话，我再看看怎么做两个列表在里面来回拖动命令。要是新功能有什么问题请随时联系我！谢谢！

**Comment by alexinea** [comment]
这样就很棒了，我还在想整两个配置面板，还存在两边同步不同步的问题呢~

**Comment by alephpiece** [comment]
先弄了个简单的😄

**Comment by FelipeRearden** [comment]
Amazing new feature @alephpiece !!!!!!!!

It was about to ask for this as well 🙏
Also, working perfect on Obsidian Mobile on iPadOS  🎉

**Comment by FelipeRearden** [comment]
Hello @alephpiece !!!!

I just wanna share with you the behavior on `Slash Commander: Standalone` of this new feature.

on `0.2.14` the commands that is checked with `Show command on new line triggering` is showing on `Slash Commander: Standalone` when the command is triggered on `inline`

If it was not possible to add the same functionality to `Slash Commander: Standalone` would mind **HIDE** the commands checked with `Show command on new line triggering` from the `Slash Commander: Standalone` for every scenario (inline + new line)? 🙏 🙏 🙏

This way I can use this new feature on `Command Trigger` without hurting my `Slash Commander: Standalone` menu  🙏 🙏 🙏

Let me know if you want me to create a new FR for this issue.

I wish you a fantastic day ☀️

**Comment by alephpiece** [comment]
Sorry for the late reply! This feature is now available for the standalone menu. Thank you!

**Comment by FelipeRearden** [comment]
> Sorry for the late reply! This feature is now available for the standalone menu. Thank you!

Thank you very much for the reply @alephpiece  🙏 🙏 🙏 🙏 🙏 🙏

Working perfect on Obsidian Mobile on iPadOS ✅

I wish you a fantastic day ☀️
